config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :restaurants do
    resources :reviews, only: %i[new create]
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/restaurant.rb
# frozen_string_literal: true

class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy
  validates :name, presence: true
  validates :address, presence: true
  validates :category, presence: true, inclusion: { in: %w[chinese italian japanese french belgian] }
end

app/models/review.rb
# frozen_string_literal: true

class Review < ApplicationRecord
  belongs_to :restaurant
  validates :content, presence: true
  validates :rating, presence: true,
                     numericality: { only_integer: true, greater_than_or_equal_to: 0, less_than_or_equal_to: 5 }
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
# frozen_string_literal: true

class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: %i[show edit update destroy]

  def index
    @restaurants = Restaurant.all
  end

  def show
    @review = Review.new
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to @restaurant, notice: 'Restaurant was successfully created'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @restaurant.update(restaurant_params)
      redirect_to @restaurant, notice: 'Restaurant was successfully updated'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @restaurant.destroy
    redirect_to restaurants_url, notice: 'Restuarant was successfully destroyed'
  end

  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category)
  end
end

app/controllers/reviews_controller.rb
# frozen_string_literal: true

class ReviewsController < ApplicationController
  before_action :set_restaurant

  def new
    @review = @restaurant.reviews.new
  end

  def create
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = @restaurant.reviews.new(review_params)

    if @review.save
      redirect_to @restaurant
    else
      render :new
    end
  end

  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
# frozen_string_literal: true

module RestaurantsHelper
end

app/helpers/reviews_helper.rb
# frozen_string_literal: true

module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/_form.html.erb
<%= simple_form_for(@restaurant) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :phone_number %>
    <%= f.input :category %>
  </div>

  <div class="form-action">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/restaurants/_restaurant.html.erb
<div id="<%= dom_id restaurant %>">

  <p>
    <strong>Name:</strong>
    <%= restaurant.name %>
  </p>

  <p>
    <strong>Address:</strong>
    <%= restaurant.address %>
  </p>

  <p>
    <strong>Phone Number:</strong>
    <%= restaurant.phone_number %>
  </p>

  <p>
    <strong>Category:</strong>
    <%= restaurant.category %>
  </p>

</div>

app/views/restaurants/index.html.erb
<h1>Restaurants</h1>

<div id="restaurants">
  <% @restaurants.each do |restaurant| %>
    <%= render restaurant %>
    <p>
      <%= link_to "Show this restaurant", restaurant %>
    </p>
  <% end %>
</div>

<%= link_to "New restaurant", new_restaurant_path %>

app/views/restaurants/new.html.erb
<h1>New restaurant</h1>

<%= render "form", restaurant: @restaurant %>

<br>

<div>
  <%= link_to "Back to restaurants", restaurants_path %>
</div>

app/views/restaurants/show.html.erb
<h1><%= @restaurant.name %></h1>
<p>Category: <%= @restaurant.category %></p>
<p>Address: <%= @restaurant.address %></p>
<p>Phone Number: <%= @restaurant.phone_number %></p>

<h2>Reviews</h2>
<% @restaurant.reviews.each do |review| %>
  <div>
    <p>
      <%= review.content %>
    </p>
  </div>
<% end %>

<h3>Add a Review</h3>
<%= render 'reviews/form', restaurant: @restaurant, review: @review %>

<div>
  <%= link_to "Back to restaurants", restaurants_path %>
</div>

app/views/reviews/_form.html.erb
<%= simple_form_for [@restaurant, @review] do |f| %>
  <%= f.input :content %>
  <%= f.submit "Add Review", class: "btn btn-success" %>
<% end %>

app/views/reviews/new.html.erb
<h1>New Review</h1>
<%= form_with model: @review, url: restaurant_reviews_path(@restaurant) do |form| %>
  <%= form.label :content %>
  <%= form.text_area :content %>

  <%= form.label :rating %>
  <%= form.number_field :rating, in: 1..5 %>

  <%= form.submit "Submit Review" %>
<% end %>